### ISSUE TITLE
LongBigArrayBigList throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jafsnano** [vigna/fastutil#103]
Trying to increment LongBigArrayBigList size worked fine until 8.1.1 version, in 8.2.0 and 8.2.1 throws this error:

`import it.unimi.dsi.fastutil.longs.LongBigArrayBigList;

public class A {

  public static void main(String[] args) throws Exception {
    LongBigArrayBigList vec = new LongBigArrayBigList();
    vec.size(2);
  }

}`

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: End index (2) is greater than big-array length (0)
        at it.unimi.dsi.fastutil.BigArrays.ensureFromTo(BigArrays.java:254)
        at it.unimi.dsi.fastutil.longs.LongBigArrays.fill(LongBigArrays.java:608)
        at it.unimi.dsi.fastutil.longs.LongBigArrayBigList.size(LongBigArrayBigList.java:377)`

**Comment by vigna** [comment]
Fixed for 8.2.1.
