### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by shendepuren** [vigna/fastutil#112]
I am getting an error trying to serialize Int2ReferenceLinkedOpenHashMap with kryo on spark.
 ```
com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: 1
Serialization trace:
c1 (com.jd.wq.dmp.realtime.entity.cateaction.CateActionBean)
at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:585)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:213)
at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:194)
at org.apache.spark.serializer.SerializationStream.writeValue(Serializer.scala:147)
at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:204)
at org.apache.spark.util.collection.WritablePartitionedPairCollection$$anon$1.writeNext(WritablePartitionedPairCollection.scala:56)
at org.apache.spark.util.collection.ExternalSorter.writePartitionedFile(ExternalSorter.scala:715)
at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:72)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
at org.apache.spark.scheduler.Task.run(Task.scala:89)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:229)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at com.esotericsoftware.kryo.serializers.MapSerializer.setGenerics(MapSerializer.java:53)
at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.write(FieldSerializer.java:563)
```

But when i change Int2ReferenceLinkedOpenHashMap to LinkedHashMap, it is ok.  Am I doing something wrong here? 

my code:

```
public class CateActionBean implements Serializable { 
        private Int2ReferenceMap<TotalCnt> c1 = new Int2ReferenceLinkedOpenHashMap<>();
...
}
```

```
public class PersonaKyroRegistrator implements KryoRegistrator{

    public void registerClasses(Kryo kryo) {
        kryo.register(TotalCnt.class);
        kryo.register(CateActionBean.class);
        kryo.register(CateActionBizService.class);
    }
```

**Comment by shendepuren** [comment]
> Well, not a single row of the stack trace belongs to fastutil, so it's a bit difficult for me to do a diagnosis. Did you try to serialize the map by itself? How large is the map when it is serialized?

My fault. I re-edited the question.

**Comment by vigna** [comment]
I don't see changes relevant to what I wrote though...

**Comment by shendepuren** [comment]
> I don't see changes relevant to what I wrote though...

i dit a test.  Serialize the map by itself is ok. but i don't understand, why does it get an error when it's a member field of a class?

**Comment by vigna** [comment]
Good question, but I would pose it to someone who knows kryo very well... and I don't. :)

**Comment by vigna** [comment]
Just as a test, would you mind to declare the field of type Int2ReferenceLinkedOpenHashMap instead of using the interface?

**Comment by shendepuren** [comment]
> Just as a test, would you mind to declare the field of type Int2ReferenceLinkedOpenHashMap instead of using the interface?

Both interface and implement have mistakes. but when i change  Int2ReferenceMap<TotalCnt> to Int2ReferenceMap , it is ok...    It's amazing. Thank you very much :)
